awk '
/fun login\(email: String/ {
  print "    fun loginWithGoogle(idToken: String) {"
  print "        val credential = com.google.firebase.auth.GoogleAuthProvider.getCredential(idToken, null)"
  print "        auth.signInWithCredential(credential)"
  print "            .addOnSuccessListener { authResult ->"
  print "                viewModelScope.launch {"
  print "                    val email = authResult.user?.email ?: return@launch"
  print "                    val name = authResult.user?.displayName ?: email.substringBefore(\"@\")"
  print "                    val user = repository.getUserSync(email)"
  print "                    if (user != null) {"
  print "                        _notifications.emit(Pair(\"Success\", \"Logged in as ${user.name}\"))"
  print "                    } else {"
  print "                        repository.createUser(User("
  print "                            email = email,"
  print "                            name = name,"
  print "                            role = Role.CUSTOMER,"
  print "                            points = 5"
  print "                        ))"
  print "                        _notifications.emit(Pair(\"Success\", \"Account created! 5 bonus points awarded.\"))"
  print "                    }"
  print "                }"
  print "            }"
  print "            .addOnFailureListener {"
  print "                viewModelScope.launch { _notifications.emit(Pair(\"Error\", it.localizedMessage ?: \"Google Sign-In failed\")) }"
  print "            }"
  print "    }"
  print ""
}
{ print }' app/src/main/java/com/example/ui/viewmodel/LoyaltyViewModel.kt > tmp.kt && mv tmp.kt app/src/main/java/com/example/ui/viewmodel/LoyaltyViewModel.kt
